# Generated by Django 5.0 on 2023-12-22 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortener',
            name='expires',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='shortener',
            name='active_duration',
            field=models.CharField(choices=[('1', '1 month'), ('3', '3 months'), ('6', '6 months'), ('12', '12 months')], max_length=2),
        ),
        migrations.AlterField(
            model_name='shortener',
            name='short_key',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='shortener',
            name='tags',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='shortener',
            name='url',
            field=models.URLField(max_length=300),
        ),
    ]
